### ISSUE TITLE
README.mdの画像リンク切れ

### ISSUE THREAD

**Issue by terasato** [runceel/Livet#37]
権限付与ありがとうございました。

README.mdの「Working with Visual Studio and Livet」のセクションで，スクリーンショットのリンク切れです。過去のコミットから復活させれば良いのでしょうか？

**Comment by runceel** [comment]
メール通知設定してるはずなのに、来なくて反応が遅れました。
translate ブランチでひっそりと作業してます（READMEは日本語がプライマリーにしようかなと思ってます）

画像は…復帰させないとですね。master ブランチじゃなければ好きにしてもらって大丈夫ですし。typo とかレベルならセルフで PR 承認してもらっても OK です！

tranalste ブランチを master にマージするので、画像は復旧させれそうなときにします。もしお手すきでやってもいいなっていう感じでしたら復旧させてセルフ承認で PR 作ってやってもらっても大丈夫です～

**Comment by runceel** [comment]
今マージしました。日本語のほう（README.md）は画像リンク切れ無い感じです。

**Comment by terasato** [comment]
作業ありがとうございます。了解しました。
