### ISSUE TITLE
Nuget ライブラリの更新

### ISSUE THREAD

**Issue by terasato** [runceel/Livet#40]
こんにちは。Nugetライブラリの更新方法が分かりませんので，お願いできませんでしょうか。お手数おかけします。

**Comment by runceel** [comment]
すいません。遅くなりました。
NuGet パッケージと VS の拡張機能をどうやるかですねぇ…

**Comment by runceel** [comment]
2.2.2 としてリリースしました。拡張機能の方も更新しました。
nupkg だけ作る目的であれば Release ビルドをして、プロジェクトの NuGet フォルダーにある nuspec ファイルのバージョン番号を任意の番号にして、NuGet フォルダーにある pack.bat をダブルクリックすると出来ます。
