### ISSUE TITLE
ViewModelA->ViewModelBのメッセージ通知

### ISSUE THREAD

**Issue by hinotama** [runceel/Livet#42]
こんにちは、

また、困ったことがあるので、改めてご連絡いたします。

ViewModelAからViewModelBへメッセージを渡したいですが、Livetはこの行動をサポートしますか。
今、MVVM Light Messengerツールで渡されます。こういう感じです。
![image](https://user-images.githubusercontent.com/10820908/65297368-bda5a080-db91-11e9-8158-9b4314d47b77.png)
http://dotnetpattern.com/mvvm-light-messenger

例えば：ViewModelAからViewModelBへメッセージを渡す。

ViewModelAのコード
```C#
MessengerInstance.Send("ToViewModelC"); //「ToViewModelC」のメッセージを渡す。
```

ViewModelBのコード
```C#
MessengerInstance.Register<string>(this, message=> 
{
    if (message == "ToViewModelC")
    {
        // 習得されたmessageで操作する
    }
});
```

ですが、Livetに変更してみたいです。このような行動はサポートがあるのですか。

ご指導のほどよろしくお願いいたします。

**Comment by hinotama** [comment]
ご返事ありがとうございます。

問題の説明が不足して申し訳ありません。改めてご説明いたします。

例えば、こういう画面があります。
- ``Main`` (Windowタイプ)
- ``User`` (UserControlタイプ)
- ``Product`` (UserControlタイプ)

``Main``画面の``MainModel``は以下の用で作成します。
```C#
public class MainModel: NotificationObject
{
    public object ViewModel { get; set; }
}
```
画面のデザインは以下のようです。

![image](https://user-images.githubusercontent.com/10820908/65847741-fbae7b80-e36c-11e9-8e64-563b410d20bf.png)


``Main``画面は2つの部分があります。上の部分は``Dock/StackPanel``で``User/Product``のボタンが入ります。下の部分は``ContentControl``で``MainModel``の``object``タイプの``ViewModel``パラメーターに``binding``します。

``User``ボタンを押すと、``MainViewModel``にあるコマンドで``MainModel``の``ViewModel``パラメーターを``new UserViewModel();``に変更します。そして、``RaisePropertyChanged("MainModel");``を呼びます。

そうすると、``Main``画面の下の``ContentControl``部分が``User``画面の内容に変更されます。

``Product``ボタンの方も同じパータンです。

上記のデザインと行動パターンは問題ないが、下記の方は・・・

![image](https://user-images.githubusercontent.com/10820908/65847751-09fc9780-e36d-11e9-99a3-0897be41bc01.png)

例えば、``User``画面に「``Product画面へ``」というボタンがあって、このボタンを押すと、``Main``画面の``ContentControl``が``Product``画面になります。

この行動は、少し困ります。``MainModel.ViewModel``を変更したいが、``MainModel``のインスタンスは``Main``画面の``MainViewModel``に作成されました。

だが、「``Product画面へ``」ボタンのコマンドは``User``画面の``UserViewModel``に組み込んでいて、``MainViewModel``の``MainModel``インスタンスをアクセスできません。

その理由で、``UserViewModel``から``MainViewModel``へ「"ToProductView"」メッセージを送りたいです。``MainViewModel``がメッセージを習得したら、``MainModel.ViewModel``を``new ProductViewModel();``に変更することができます。

ご指導のやり方は「``Model``から``PropertyChanged``イベントや``CollectionChanged``イベントが発行されて、それを``ViewModelB``で受け取り処理するといった流れ」が、上記の例にとって、``MainModel``インスタンスは``MainViewModel``に作成されたことで、``UserViewModel``はそのインスタンスをどうすれば習得できるのか分かりませんが・・・

**Comment by k-oshiro0322** [comment]
私は以下の様にして実装しましたが、他にも良い実装方法があれば知りたいです。

UserViewModelからUserViewに対してメッセンジャーで通知します。

```
Messenger.Raise(new InteractionMessage("UserViewModel"));
```


```
<l:InteractionMessageTrigger Messenger="{Binding Messenger}"  MessageKey="UserViewModel">
  <local:MainViewModelSampleAction />
</l:InteractionMessageTrigger>
```

ActionにてUserControlより親のコントロールを探し、そのDataContextを取得するとMainViewModelにアクセス出来ます。
親のWindowを探す方法は割愛します。

```
public class MainViewModelSampleAction : TriggerAction<FrameworkElement> {

    protected override void Invoke(object parameter) {
        //Windowオブジェクトを探す
        var window = CustomHelper.FindParent<Window>(this.AssociatedObject);
        if (window == null) {
            return;
        }

        var vm = window.DataContext as MainViewModel;

        if (vm != null) {
           //vmのメソッドを呼び出す
        }
    }

}

```

**Comment by YoshihiroIto** [comment]
@hinotama さんこんにちは。

画面デザインだけを見てサンプルを実装してみました。
https://github.com/YoshihiroIto/WpfSample/

このサンプルの趣旨は教科書通りのMVVMでつくってみたら。です。
いくつかある回答の一つだと思ってください。

また、@runceel  さんのおっしゃっている
「まず、前提としてアプリケーションのコアの状態やロジックなどは Model レイヤーで行います。」を実装したことになります。

作りとしては、
メインウィンド状態を扱うモデルを用意し、各ビューはそれを一方的に参照しモデルの変更をビュー観点で表現します。
複数ビューモデル間のやり取りなどは発生しする構造にはなっていません。

このサンプルが言いたいことは、
MVVMの何たるかです。モデルはビューモデルやビューに引きずられる関係になってはいけない絶対原則を守ることにより依存関係が簡素に保たれます。

繰り返しになりますが、
いくつかある回答の一つだと思ってください。

**Comment by runceel** [comment]
Livet 自体には Window 内の一部を画面遷移させるみたいな機能はないので、ここで他の方に回答していただいたように何らかの仕組みを作る必要があります。

もしくは Prism を使うと、画面の一部を Region として定義して、その中を任意のユーザーコントロールに切り替える仕組みがあるので楽ですね。

ちょっと面白そうなので私も時間をとって作ってみようと思います。

**Comment by runceel** [comment]
とりあえず、どの画面がアクティブなのかとかは Model としては興味無いなら ViewModel あたりでさくっとページ切り替え出来ると楽そうなので、画面遷移用のメッセージを投げる `InteractionMessenger` のインスタンスを static な領域に確保して、そこにメッセージ投げると画面遷移するようにしてみました。

https://github.com/runceel/Livet-samples

![wpfnav](https://user-images.githubusercontent.com/79868/66022275-622bc900-e528-11e9-8a25-610cf6b92947.gif)

**Comment by runceel** [comment]
まぁ、いろいろなやり方があるのと、後は画面遷移を本格的にしたくてヒストリー機能が欲しい etc... とかになってくると、もしかすると汎用画面遷移部品として作りこむくらいした方が、いいケースもありえますね。

**Comment by hinotama** [comment]
@k-oshiro0322 @YoshihiroIto @runceel 
ご返事ありがとうございます。

色々な方法で組み込むことができますね。
私も別のやり方でやってみたいが、今は少し他のことに集中しなければならないですが・・・
・・・といえども、皆さんのご意見は役に立ちます。

自分の質問の答えを見つけたが、他の方が質問があるかもしれないので、このイシューを閉じることは@runceelさんにお任せ致します。ｍ（＿　＿；）ｍ

お忙しいところ、ご指導いただき、ありがとうございました。ｍ（＿　＿；）ｍ

**Comment by runceel** [comment]
@hinotama 
では閉じますね～。
また、何かあればお気軽に質問ください。ちょっとメールが埋もれて気づくのが遅くなることはありますが、その場合は Twitter で @okazuki にメンションいただければ気づくのが早くなると思います。
