### ISSUE TITLE
VisualStudio2019にて新規プロジェクトでLivetテンプレートを使用するとClickOnce発行ができません。

### ISSUE THREAD

**Issue by KazuyaOkuda** [runceel/Livet#47]
奥田と申します。

VisualStudio2019にて新規プロジェクトでLivetテンプレートを使用するとClickOnceによる発行ができません。
これは、Livetのテンプレートに問題があるのでしょうか？
それとも、VisualStudio2019側に問題があるのでしょうか？

**Comment by runceel** [comment]
@KazuyaOkuda 
プロジェクトテンプレートを SDK Style にしたのですが、これが ClickOnce に対応してないのですかねぇ？

**Comment by runceel** [comment]
@KazuyaOkuda 
以下のようなブログ記事もあるので SDK Style のプロジェクト自体が ClickOnce に対応していないのかもしれません。
https://www.flexlabs.org/2020/01/deploying-clickonce-apps-with-sdk-style-projects

ClickOnce を使いたい場合は上記記事の内容をしてもらうか以下の手順で普通の WPF プロジェクトから始めてもらうのがいいと思います。

1. WPF プロジェクトを作成(.NET Framework)
2. LivetCask を NuGet から導入
3. Views / ViewModels などのフォルダーを作って、そこで開発をしていく

**Comment by KazuyaOkuda** [comment]
@runceel 
ご返信ありがとうございます。
 SDK Style のプロジェクト自体が ClickOnce に対応していない可能性について、理解しました。
WPFプロジェクトから作成するか、MSIXを検討することにします。
ありがとうございました。

**Comment by runceel** [comment]
では、このIssueはクローズしますね。
もし、追加で何かあれば再オープンか別途Issueを立ててください。

ありがとうございました。
