### ISSUE TITLE
FolderSelectionMessageでの複数選択

### ISSUE THREAD

**Issue by soi013** [runceel/Livet#59]
FolderSelectionMessageにおいて、複数のファイルを選択することはできますか？
さらに言えば、フォルダとファイルを混ぜて複数選択することは可能ですか。

よろしくおねがいします。

**Comment by runceel** [comment]
@soi013 
以下のファイルを見る限り特にそのような指定をするオプションはないような気がします。
https://github.com/runceel/Livet/blob/master/LivetCask.Extensions/Dialogs/CommonOpenFileFolderSelectionDialog.cs

ベースにしている WindowsAPICodePack に、そのような API があれば Livet の Message から指定可能なような口を提供することは可能だと思います。

**Comment by soi013** [comment]
Microsoft.WindowsAPICodePack.DialogsのCommonOpenFileDialogにMultiselectというプロパティがあるので、これを使うように変更すればよいでしょうか？
私からPR送っても良いでしょうか。

> ちなみに、複数ファイルの選択は一般的だと思いますがフォルダとファイルを混ぜて複数選択って Windows で普通にできますか？あまり見た記憶がないのですが。

たしかによく考えると無いですね。あまり需要もなさそうです。

**Comment by runceel** [comment]
@soi013 
PR 送っていただければ対応します！
