### ISSUE TITLE
.NET 6 で FolderBrowserDialog を開こうとするとエラー

### ISSUE THREAD

**Issue by shinta0806** [runceel/Livet#70]
Livet 4.0.1 + .NET 6 + VS 2022 で FolderBrowserDialog を開こうとするとエラーが発生します。

Something errors were occurred.
Could not load file or assembly 'Microsoft.WindowsAPICodePack.Shell, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. 指定されたファイルが見つかりません。
![error](https://user-images.githubusercontent.com/7196473/141667037-d423354d-aaa4-4f2e-80fc-681f5dac9733.png)

ターゲットフレームワークを .NET 5 にするとエラーは発生しません。

テストプログラム：
https://github.com/shinta0806/TestFolderBrowserDialog

**Comment by runceel** [comment]
4.0.2-pre202111140437 で修正しました。

**Comment by shinta0806** [comment]
修正ありがとうございました。

**Comment by runceel** [comment]
v4.0.2 をリリースしました
